stages:
  - build
  - ci
  - release
default:
  before_script:
    - env | sort
  retry:
    max: 2
    when: runner_system_failure
  image: ${CI_REGISTRY_IMAGE}/agibot-forge/dev:latest
variables:
  DEV_ARTIFACTORY: artifactory_genie
  ARTIFACTORY_USER: gabriel

include:
  - local: .gitlab/workflows/**.yml
