default_install_hook_types:
  - post-checkout
  - post-merge
  - post-rewrite
  - pre-push
  - pre-commit
default_stages:
  - manual
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
        args:
          - '--assume-in-merge'
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
        args:
          - '--pytest-test-first'
        exclude: ^tests/utils/
      - id: no-commit-to-branch
        stages:
          - pre-push
      - id: sort-simple-yaml
        files: .pre-commit-config.yaml
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.5
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
        stages:
          - pre-commit
        exclude: |
          (?x)(
              ^(src/video_decoder/include/core/.*) |
              ^(src/video_decoder/src/core/.*)
          )
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [pyyaml]
        types: [file]
        files: (\.cmake|CMakeLists.txt)(.in)?$
        stages:
          - pre-commit
        exclude: |
          (?x)(
              ^(cmake/configure/ConanProvider.cmake) |
              ^(cmake/configure/ExtractVersion.cmake) |
              ^(cmake/configure/GitInfo.cmake)
          )
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
        stages:
          - pre-commit
          - pre-push
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
        stages:
          - pre-commit
          - pre-push
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
      - id: pyproject-fmt
        name: pyproject-fmt
        entry: pyproject-fmt
        language: python
        files: '(^|/)pyproject\.toml$'
        types:
          - toml
      - id: codespell
        name: codespell
        entry: codespell
        language: python
        types:
          - text
