build:
  tags:
    - genie-gpu-4090
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-?(a|b|rc)(0|[1-9][0-9]*)?)?$/
  artifacts:
    paths:
      - dist
  script:
    - conan remote login ${DEV_ARTIFACTORY} ${ARTIFACTORY_USER} -p ${ARTIFACTORY_PASSWORD}
    - make install pyi build
  stage: build
