#!/bin/bash
set -euo pipefail

# Validate input
if [[ -z "${1:-}" ]]; then
    echo "Usage: $0 <VERSION>"
    echo "Example: $0 24.10"
    exit 1
fi

# Configuration
VERSION="$1"
IMAGE="nvcr.io/nvidia/pytorch:${VERSION}-py3"
OUTPUT_DIR="$(dirname "$0")/../constraints"
OUTPUT_FILE="${OUTPUT_DIR}/${VERSION}.txt"
CMD="docker run --rm --entrypoint= ${IMAGE} pip list --format=freeze 2>/dev/null"

# Generate constraints
mkdir -p "$OUTPUT_DIR"
{
    echo "# Generated by: ${CMD}"
    eval "$CMD"
} > "$OUTPUT_FILE"

echo "Created: $(realpath ${OUTPUT_FILE})"
