name: cibuildwheel

on:
  workflow_call:
    inputs:
      auto:
        description: Build wheels for auto archs
        required: true
        type: boolean
      extra:
        description: Build wheels for aarch64
        required: true
        type: boolean

jobs:
  build_wheels:
    name: ${{ matrix.os }}, ${{ matrix.arch }}, ${{ matrix.build }} wheels
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]
        arch: [x86_64]
        build: [manylinux]
        qemu_arch: [aarch64]

    steps:
      - uses: actions/checkout@v4
        if: >
          inputs.auto && !contains(matrix.qemu_arch, matrix.arch) ||
          inputs.extra && contains(matrix.qemu_arch, matrix.arch)
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: runner.os == 'Linux' && inputs.extra && contains(matrix.qemu_arch, matrix.arch)

      - name: Build wheels
        if: >
          inputs.auto && !contains(matrix.qemu_arch, matrix.arch) ||
          inputs.extra && contains(matrix.qemu_arch, matrix.arch)
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: '*${{ matrix.build }}*'
          CIBW_BEFORE_ALL: >
            yum config-manager --add-repo http://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo &&
            yum -y install cuda-nvcc-12-9 cuda-cudart-devel-12-9 cuda-nvrtc-devel-12-9 nvidia-driver-cuda-libs &&
            yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm &&
            yum install -y ffmpeg ffmpeg-devel && rm -rf /var/cache/yum && yum clean all
          CIBW_ENVIRONMENT: >
            PATH=$PATH:/usr/local/cuda/bin
            CUDACXX=/usr/local/cuda/bin/nvcc
            LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

      - name: Upload wheels
        if: >
          inputs.auto && !contains(matrix.qemu_arch, matrix.arch) ||
          inputs.extra && contains(matrix.qemu_arch, matrix.arch)
        uses: actions/upload-artifact@v4
        with:
          name: cibw-${{ matrix.os }}-${{ matrix.build }}-${{ matrix.arch }}
          path: wheelhouse/*.whl
